### PR TITLE
libpod/container_internal_linux: Allow gids that aren't in the group file

### LINKED ISSUE #1937: libpod crashes when numeric gid is not in group file
[//]: # **kind bug**

**Description**

When an image config sets [`config.User`][1] to a numeric value (like `1000:1000`), but those values do not exist in the container's `/etc/passwd` and/or `/etc/group`, libpod is currently breaking.  However, the OCI spec [requires converters to copy numeric `uid` and `gid` to the runtime config without attempting to look them up][2].

**Steps to reproduce the issue:**

```console
$ podman version
Version:       0.11.2-dev
Go Version:    go1.10.3
Git Commit:    "5f6ad82524ca7a3281c8464c84b4f9be4ff90aef"
Built:         Tue Dec  4 11:05:15 2018
OS/Arch:       linux/amd64
$ podman run --rm -it registry.svc.ci.openshift.org/ci-op-zvml7cd6/pipeline:installer --help
error creating temporary passwd file for container 228f6e9943d6f18b93c19644e9b619ec4d459a3e0eb31680e064eeedf6473678: unable to get gid 1000 from group file: no matching entries in group file
```

with an image built from [this][3].  I'm skipping `podman info`, because I don't think it matters, and I'm working up a fix for this myself ;).

**Describe the results you expected:**

A successful container run.

[1]: https://github.com/opencontainers/image-spec/blame/v1.0.1/config.md#L118-L123
[2]: https://github.com/opencontainers/image-spec/blame/v1.0.1/conversion.md#L70
[3]: https://github.com/openshift/installer/blob/v0.5.0/images/installer/Dockerfile.ci

### PR DESCRIPTION
**Pull request by wking**
When an image config sets [`config.User`][1] to a numeric group (like `1000:1000`), but those values do not exist in the container's `/etc/group`, libpod is currently breaking:

```console
$ podman run --rm registry.svc.ci.openshift.org/ci-op-zvml7cd6/pipeline:installer --help
error creating temporary passwd file for container 228f6e9943d6f18b93c19644e9b619ec4d459a3e0eb31680e064eeedf6473678: unable to get gid 1000 from group file: no matching entries in group file
```

However, the OCI spec [requires converters to copy numeric `uid` and `gid` to the runtime config verbatim][2].

With this commit, I'm frontloading the "is groupspec an integer?" check and only bothering with `lookup.GetGroup` when it was not.

I've also removed a few `.Mounted` checks, which are originally from 00d38cb3 (#110).  We don't need a mounted container filesystem to translate integers.  And when the lookup code needs to fall back to the mounted root to translate names, it can handle erroring out internally (and looking it over, it seems to do that already).

Fixes #1937

[1]: https://github.com/opencontainers/image-spec/blame/v1.0.1/config.md#L118-L123
[2]: https://github.com/opencontainers/image-spec/blame/v1.0.1/conversion.md#L70

### CODE REVIEW

File: libpod/container_internal_linux.go [hunk 1]
```diff
@@ -827,17 +820,16 @@ func (c *Container) generatePasswd() (string, error) {
...
-			return "", errors.Wrapf(ErrCtrStateInvalid, "container %s must be mounted in order to translate group field for passwd record", c.ID())
-		}
-		group, err = lookup.GetGroup(c.state.Mountpoint, groupspec)
-		if err != nil {
-			if err == user.ErrNoGroupEntries {
+		ugid, err := strconv.ParseUint(groupspec, 10, 32)
+		if err == nil {
+			gid = int(ugid)
+		} else {
+			group, err := lookup.GetGroup(c.state.Mountpoint, groupspec)
```
Comment (mheon) [inline libpod/container_internal_linux.go]: Should this be patched into lookup.GetGroup(), instead of working around it here? We use GetGroup in Buildah, so if possible we'd like to share the fix with them

Comment (wking) [reply libpod/container_internal_linux.go]: > Should this be patched into `lookup.GetGroup()`, instead of working around it here?

Well, there's also `Group.Name`, `Group.Pass` and `Group.List` in `user.Group` that we'd be unable to populate.  So what I'm doing here (not hitting the container filesystem at all, because we only need the GID) doesn't seem like a good fit for `GetGroup`.

But you could have `GetGroup` return a `*user.Group` with only `Gid` set and still return `ErrNoGroupEntries` so the caller that wanted those other fields but could limp by with just the GID could just ignore `ErrNoGroupEntries` instead of performing their own integer check.  Should I add a commit to this PR to make that `GetGroup` change?

Comment (rhatdan) [reply libpod/container_internal_linux.go]: Yes lets do that

Comment (wking) [reply libpod/container_internal_linux.go]: > Yes lets do that

Ok, pushed 7fae5d5 with this logic.

File: pkg/lookup/lookup.go [hunk 2]
```diff
@@ -124,12 +126,17 @@ func GetUser(containerMount, userIDorName string) (*user.User, error) {
 	if len(users) > 0 {
 		return &users[0], nil
 	}
+	if !inputIsName {
+		return &user.User{Uid: uid}, user.ErrNoPasswdEntries
+	}
```
[the remark this answers is not in the document]
Comment (wking) [reply pkg/lookup/lookup.go]: @rhatdan signed off on this approach [here][1].  I don't care either way, but once y'all have made up your minds, let me know if I should drop this commit ;).

[1]: https://github.com/containers/libpod/pull/1940#discussion_r238827430

[the remark this answers is not in the document]
Comment (vrothberg) [reply pkg/lookup/lookup.go]: Sorry, entirely my fault. I am cool with it :)
