### PR TITLE
Podman pod stats -- fix GO template output

### LINKED ISSUE #2258: when use "podman pod stats --format '{{GO template}}'","--format" option doesn't work
/kind bug

**Description**

When i use `podman pod stats --format`  to view resource usage statistics for the pods,if I use a Go template,`--format` option does not work.

**Steps to reproduce the issue:**

1. create a pod.
```
# podman pod create
3cc2ebb00c7512f3ba41ef4f2d8c28181c89dad21b603fb9c4bba46ad20cfb51

# podman pod ps
POD ID         NAME             STATUS    CREATED          # OF CONTAINERS   INFRA ID
3cc2ebb00c75   sad_heisenberg   Running   16 seconds ago   1                 adae4b38c879
```
2. use a GO template to view resource usage statistics.
```
# podman pod stats -l --no-stream --format "{{.MemUsage}}"

POD            CID            NAME         CPU %  MEM USAGE/ LIMIT    MEM %  NET IO              BLOCK IO            PIDS
3cc2ebb00c75   adae4b38c879   3cc2ebb00c   5.85%  1.032MB / 67.51GB   0.00%  978B / 6.541kB      -- / --             1
```
As you can see, the output of the command is not in the specified format.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:       1.0.0
Go Version:    go1.11.4
Git Commit:    "49780a1cf10d572edc4e1ea3b8a8429ce391d47d"
Built:         Mon Jan 14 15:38:17 2019
OS/Arch:       linux/amd64
```

**Output of `podman info`:**

```
host:
  BuildahVersion: 1.6-dev
  Conmon:
    package: podman-1.0.0-1.git82e8011.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 49780a1cf10d572edc4e1ea3b8a8429ce391d47d'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 6033768448
  MemTotal: 67505704960
  OCIRuntime:
    package: runc-1.0.0-67.dev.git12f6a99.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: d164d9b08bf7fc96a931403507dd16bced11b865
      spec: 1.0.1-dev
  SwapFree: 33820766208
  SwapTotal: 33820766208
  arch: amd64
  cpus: 24
  hostname: fedora29
  kernel: 4.18.16-300.fc29.x86_64
  os: linux
  rootless: false
  uptime: 123h 51m 48.15s (Approximately 5.12 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
```

### PR DESCRIPTION
**Pull request by baude**
Go templates were not being processed or printed correctly for podman
pod stats.  Added the ability to do templates as well as honor the
table identifier.

Fixes #2258

Signed-off-by: baude <bbaude@redhat.com>

### CODE REVIEW

File: cmd/podman/pod_stats.go [hunk 1]
```diff
@@ -177,28 +207,90 @@ func podStatsCmd(c *cliconfig.PodStatsValues) error {
...
+	}
+	// Flush the writer
+	return w.Flush()
+
+}
+
+func outputToStdOut(stats []*podStatOut) {
+	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
+	outFormat := ("%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n")
+	//fmt.Printf(outFormat, "POD", "CID", "NAME", "CPU %", "MEM USAGE/ LIMIT", "MEM %", "NET IO", "BLOCK IO", "PIDS")
```
Comment (mheon) [inline cmd/podman/pod_stats.go]: Can we ditch this if we're not using it anymore?

Comment (baude) [reply cmd/podman/pod_stats.go]: you betcha

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
I'm a bit concerned that we're adding tabwriter stuff back into the main code path, which could have the same perf implications that `podman ps` had that we needed a rewrite for.

On the other hand, I doubt we see as many pods as we did containers, so let's cross that bridge when we come to it.

/lgtm

**Comment by mheon** [comment]
Hey, bot, LGTM label please?

**Comment by baude** [comment]
> I'm a bit concerned that we're adding tabwriter stuff back into the main code path, which could have the same perf implications that `podman ps` had that we needed a rewrite for.
> 
> On the other hand, I doubt we see as many pods as we did containers, so let's cross that bridge when we come to it.
> 
> /lgtm

@mheon it wasnt tabwriter that had the perf implications, it was the use of the go templating for regular output and the multiple serializations needed for that.
