### PR TITLE
fix bug podman cp directory

### LINKED ISSUE #2836: podman cp does not copy folders
/kind bug

**Steps to reproduce the issue:**

Compare podman and docker:

```
$ ls /tmp/new_folder_02/
$
$ podman cp /tmp/new_folder_02 sweet_hellman:/home/
$ podman exec sweet_hellman ls /home/
$
$ sudo docker cp /tmp/new_folder_02 elated_kalam:/home/
$ sudo docker exec elated_kalam ls /home/
new_folder_02
$
```

**Output of `podman version`:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.11.5
OS/Arch:            linux/amd64
```

### PR DESCRIPTION
**Pull request by QiWang19**
close #2836 
`podman cp` used to copy the contents under the source directory to the destination. But according to the specification in podman-cp.md. it should copy the whole directory to the destination if the destination directory already exists.
- src dir ends with /., copy the contents to dest dir
- src dir does not end with /.
    - dest dir `/home` does not exist, copy the contents
    - dest dir `/home` exists, copy the directory

```
$ sudo podman cp /home/qiwan/Documents/empty 7c47:/home
$ sudo podman exec -it 7c47 ls /home
$

$ sudo podman cp /home/qiwan/Documents/empty 7c47:/home
$ sudo podman exec -it 7c47 ls /home
empty

```

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

File: cmd/podman/cp.go [hunk 1]
```diff
@@ -241,6 +242,11 @@ func copy(src, destPath, dest string, idMappingOpts storage.IDMappingOptions, ch
 	if !srcfi.IsDir() && !strings.HasSuffix(dest, string(os.PathSeparator)) {
 		destdir = filepath.Dir(destPath)
 	}
+	_, err = os.Stat(destdir)
+	if err != nil && !os.IsNotExist(err) {
+		return errors.Wrapf(err, "error checking directory %q", destdir)
+	}
+	destDirIsExist := !os.IsNotExist(err)
```
Comment (mheon) [inline cmd/podman/cp.go]: Can't you set this to `err == nil`?

Comment (QiWang19) [reply cmd/podman/cp.go]: yes, I should...

File: cmd/podman/cp.go [hunk 2]
```diff
@@ -241,6 +242,11 @@ func copy(src, destPath, dest string, idMappingOpts storage.IDMappingOptions, ch
 	if !srcfi.IsDir() && !strings.HasSuffix(dest, string(os.PathSeparator)) {
 		destdir = filepath.Dir(destPath)
 	}
+	_, err = os.Stat(destdir)
+	if err != nil && !os.IsNotExist(err) {
+		return errors.Wrapf(err, "error checking directory %q", destdir)
+	}
+	destDirIsExist := (err == nil)
```
Comment (kunalkushwaha) [inline cmd/podman/cp.go]: Though this save lines in code, but make less readable.

**Comment by TomSweeneyRedHat** [comment]
LGTM
