### PR TITLE
Fix bug podman reset to not remove $XDG_RUNTIME_DIR 

### LINKED ISSUE #4831: 'podman system reset' shouldn't nuke unrelated things in $XDG_RUNTIME_DIR
/kind bug

**Description**

I tried resetting the rootless Podman storage using `podman system reset` a few times over the last week. On at least one occasion it tried to remove almost everything inside `$XDG_RUNTIME_DIR`, and not just the container bits like `$XDG_RUNTIME_DIR/overlay-*` or `$XDG_RUNTIME_DIR/containers`. Among the things that disappeared were the session D-Bus, Pipewire and Wayland sockets. The attempt to remove `$XDG_RUNTIME_DIR/doc` which is a FUSE mount point for Flatpak even led to:
```
Error: unlinkat /run/user/1000/doc/by-app/org.gnome.Documents: function not implemented
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This didn't happen on every `podman system reset` run, though. Other times it seemed to restrict itself to the relevant container-specific directories.

**Output of `podman version`:**

```
Version:            1.7.0-rc2
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.5
  podman version: 1.7.0-rc2
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.2-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.2, commit: 186a550ba0866ce799d74006dab97969a2107979'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 1125044224
  MemTotal: 8107823104
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 4133482496
  SwapTotal: 4133482496
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: kolache
  kernel: 5.4.7-200.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 50m 25.39s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/rishi/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/rishi/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /run/user/1000/containers
  VolumePath: /home/rishi/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-0.4.rc2.fc31.x86_64
```

### PR DESCRIPTION
**Pull request by QiWang19**
In some older systems, we point the temporary directory to /run/user/1000 which leads podman system reset to clear unrelated files under XDG_RUNTIME_DIR. This patch only removes TmoDir if it is not the same as the XDG_RUNTIME_DIR.
fix #4831 
Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
We still need to remove the tmp dir, we just want to be more selective about what we're removing in it - only the files that Podman create, not anything else

**Comment by QiWang19** [comment]
@mheon @rhatdan PTAL

File: libpod/reset.go [hunk 1]
```diff
@@ -87,12 +88,28 @@ func (r *Runtime) Reset(ctx context.Context) error {
...
-			logrus.Error(prevError)
+
+	runtimeDir, err := util.GetRuntimeDir()
+	if err != nil {
+		return err
+	}
+	tempDirs := []string{r.config.TmpDir}
+	if r.config.TmpDir == runtimeDir {
+		tempDirs = []string{
+			filepath.Join(r.config.TmpDir, r.store.GraphDriverName()+"-containers"),
```
Comment (QiWang19) [inline libpod/reset.go]: @rhatdan should this also remove `filepath.Join(r.config.TmpDir, r.store.GraphDriverName())` ?

**Comment by QiWang19** [comment]
@rhatdan @TomSweeneyRedHat @mheon PTAL

File: libpod/reset.go (hunk 1 above)
Comment (rhatdan) [reply libpod/reset.go]: Yes if it exists.

**Comment by rhatdan** [comment]
@QiWang19 Please rebase and repush.

File: libpod/reset.go (hunk 1 above)
Comment (QiWang19) [reply libpod/reset.go]: should  "containers" under TmpDir in the path that we need to remove?
`/TmpDir/containers/overlay` instead of `/TmpDir/overlay`

or we just need to remove `/TmpDir/containers` instead of hardcode these path all

**Comment by rhatdan** [comment]
LGTM
@mheon PTAL

File: libpod/reset.go (hunk 1 above)
Comment (rhatdan) [reply libpod/reset.go]: Just remove containers.

**Comment by QiWang19** [comment]
@mheon @rhatdan PTAL

**Comment by mheon** [comment]
Code LGTM

@debarshiray Any chance you can test this one and verify it works as expected?
