### PR TITLE
fix mandatory parameter in login/logout

### LINKED ISSUE #5146: podman login with different mandatory parameter than docker login
/kind bug

**Description**

Ran into this problem, when I was checking if scripts developed for docker were running with podman.

podman supposed to be compatible to docker in terms of parameters. However, there are still breaking differences:

```shell
docker --version && docker login --help

Docker version 1.13.1, build 07f3374/1.13.1

Usage:  docker login [OPTIONS] [SERVER]

Log in to a Docker registry

Options:
      --help              Print usage
  -p, --password string   Password
  -u, --username string   Username
```

whereas:
```shell
podman --version && podman login --help

podman version 1.8.0

Login to a container registry

Description:
  Login to a container registry on a specified server.

Usage:
  podman login [flags] REGISTRY

Examples:
  podman login -u testuser -p testpassword localhost:5000
  podman login -u testuser -p testpassword localhost:5000
  podman login --authfile authdir/myauths.json quay.io

Flags:
      --authfile string   Path of the authentication file. Use REGISTRY_AUTH_FILE environment variable to override
      --cert-dir string   Pathname of a directory containing TLS certificates and keys used to connect to the registry
      --get-login         Return the current login user for the registry (default true)
  -p, --password string   Password for registry
      --password-stdin    Take the password from stdin
      --tls-verify        Require HTTPS and verify certificates when contacting registries (default true)
  -u, --username string   Username for registry
```
The issue the mandatory parameter (REGISTRY) for the podman command. This breaks any compatibility.

**Describe the results you expected:**

No additional mandatory parameter for parameter inherited from docker.

### PR DESCRIPTION
**Pull request by QiWang19**
fix #5146
Insted of using a registry as mandatory parameter, this path allows podman to use the first registry from registries.conf.

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

File: cmd/podman/logout.go [hunk 1]
```diff
@@ -51,10 +53,16 @@ func logoutCmd(c *cliconfig.LogoutValues) error {
 	if len(args) > 1 {
 		return errors.Errorf("too many arguments, logout takes at most 1 argument")
 	}
+	var server string
 	if len(args) == 0 && !c.All {
-		return errors.Errorf("registry must be given")
+		registriesFromFile, err := registries.GetRegistries()
+		if err != nil || len(registriesFromFile) == 0 {
+			return errors.Errorf("registry must be given")
```
Comment (TomSweeneyRedHat) [inline cmd/podman/logout.go]: suggest:
"no registries found in registries.conf, a registry must be provided"

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 looks like you've some test unhappiness that needs to be tended to.

**Comment by rhatdan** [comment]
@QiWang19 Please fix the tests so we can get this merged.

**Comment by QiWang19** [comment]
@rhatdan @TomSweeneyRedHat  we can get this in

File: test/e2e/login_logout_test.go [hunk 2]
```diff
@@ -113,6 +113,18 @@ var _ = Describe("Podman login and logout", func() {
 		Expect(session).To(ExitWithError())
 	})
 
+	It("podman login and logout without registry parameter", func() {
+		SkipIfRootless()
+		session := podmanTest.Podman([]string{"login", "-u", "podmantest", "-p", "test"})
+		session.WaitWithDefaultTimeout()
+		Expect(session.LineInOutputContains("docker.io"))
+		Expect(session.ExitCode()).To(Not(Equal(0)))
```
Comment (TomSweeneyRedHat) [inline test/e2e/login_logout_test.go]: I think this is testing the case when there's no registry in registry.conf and it fails.  Can we test the case when there is an entry in registries.conf that woud succeed?

**Comment by rhatdan** [comment]
/approve
/lgtm
/hold
hold cancel when tests pass.

**Comment by TomSweeneyRedHat** [comment]
LGTM
