### PR TITLE
fix cp none exists dest path ends with '/'

### LINKED ISSUE #3894: podman cp: unexpected mkdir on symlink expansion
`podman cp` into a container, when the destination argument is a symlink pointing to a nonexistent path, and includes a trailing slash, will (surprisingly) mkdir that path:
```
# podman run -d --name cpc alpine sh -c 'sleep 999'
2c216ec654f5062d444d600f4dfabace3b01418b518fecafa5ba3e4074127655

! Create three tmp directories, d1 d2 d3, the first two with 
! a symlink 'x' pointing nowhere
# podman exec cpc sh -c 'mkdir /tmp/d1;ln -s /tmp/nonesuch1 /tmp/d1/x'
# podman exec cpc sh -c 'mkdir /tmp/d2;ln -s /tmp/nonesuch2 /tmp/d2/x'
# podman exec cpc sh -c 'mkdir /tmp/d3'
# podman exec cpc ls -lR /tmp
/tmp:
total 24
drwxr-xr-x    2 root     root          4096 Aug 27 19:35 d1
drwxr-xr-x    2 root     root          4096 Aug 27 19:35 d2
drwxr-xr-x    2 root     root          4096 Aug 27 19:35 d3

/tmp/d1:
total 0
lrwxrwxrwx    1 root     root            14 Aug 27 19:35 x -> /tmp/nonesuch1

/tmp/d2:
total 0
lrwxrwxrwx    1 root     root            14 Aug 27 19:35 x -> /tmp/nonesuch2

/tmp/d3:
total 0

! Create a file and copy it into the container in three different ways
# echo hi >/tmp/myfile
# podman cp /tmp/myfile cpc:/tmp/d1/x
# podman cp /tmp/myfile cpc:/tmp/d2/x/     <<<<---- note trailing slash!
# podman cp /tmp/myfile cpc:/tmp/d3/x
# podman exec cpc ls -lR /tmp
/tmp:
total 36
drwxr-xr-x    2 root     root          4096 Aug 27 19:35 d1
drwxr-xr-x    2 root     root          4096 Aug 27 19:35 d2
drwxr-xr-x    2 root     root          4096 Aug 27 19:36 d3
-rw-r--r--    1 root     root             3 Aug 27 19:36 nonesuch1    <<<<< weird
drwxr-xr-x    2 root     root          4096 Aug 27 19:36 nonesuch2    <<<<< weirder

/tmp/d1:
total 0
lrwxrwxrwx    1 root     root            14 Aug 27 19:35 x -> /tmp/nonesuch1

/tmp/d2:
total 0
lrwxrwxrwx    1 root     root            14 Aug 27 19:35 x -> /tmp/nonesuch2

/tmp/d3:
total 4
-rw-r--r--    1 root     root             3 Aug 27 19:36 x

/tmp/nonesuch2:
total 4
-rw-r--r--    1 root     root             3 Aug 27 19:36 myfile
```
When copying to `/tmp/d1/x`, where x points to nonexistent `/tmp/nonesuch1`, podman created the file `/tmp/nonesuch1`. This is weird: I would've expected an error (dangling symlink). But this is the same behavior as docker-1.13.1-103.git7f2769b.el7, so maybe we have to live with it.

When copying to `/tmp/d2/x/`, same as above but with a trailing slash, podman actually `mkdir()s` the dangling nonexistent directory, then places the file in that directory with the same name as the source file. This, I think, is bizarre and entirely wrong. (docker fails with 'no such directory').

podman master @ f221c6101934fccbd6705f3b387aadc9ae710f66

### PR DESCRIPTION
**Pull request by QiWang19**
close #3894
This patch will let podman cp return 'no such file or directory' error if DEST_PATH does not exist and ends with / when copying file.

```
$ podman run -d --name cpc alpine sh -c 'sleep 999'
$ podman exec cpc sh -c 'mkdir /tmp/d1;ln -s /tmp/nonesuch1 /tmp/d1/x'
$ podman exec cpc sh -c 'mkdir /tmp/d2;ln -s /tmp/nonesuch2 /tmp/d2/x'
$ podman exec cpc sh -c 'mkdir /tmp/d3'
$ podman exec cpc ls -lR /tmp
/tmp:
total 12
drwxr-xr-x    2 root     root          4096 Sep 24 14:45 d1
drwxr-xr-x    2 root     root          4096 Sep 24 14:45 d2
drwxr-xr-x    2 root     root          4096 Sep 24 14:45 d3

/tmp/d1:
total 0
lrwxrwxrwx    1 root     root            14 Sep 24 14:45 x -> /tmp/nonesuch1

/tmp/d2:
total 0
lrwxrwxrwx    1 root     root            14 Sep 24 14:45 x -> /tmp/nonesuch2

/tmp/d3:
total 0

$ podman cp /tmp/myfile cpc:/tmp/d1/x
$ podman cp /tmp/myfile cpc:/tmp/d2/x/
Error: failed to get stat of dest path /home/qiwan/.local/share/containers/storage/overlay/82311cd5e4e276073e44ad65eaeec65a048a3141d447d4b46393b1c3fac64168/merged/tmp/nonesuch2: stat /home/qiwan/.local/share/containers/storage/overlay/82311cd5e4e276073e44ad65eaeec65a048a3141d447d4b46393b1c3fac64168/merged/tmp/nonesuch2: no such file or directory
$ podman cp /tmp/myfile cpc:/tmp/d3/x
$ podman exec cpc ls -lR /tmp
/tmp:
total 16
drwxr-xr-x    2 root     root          4096 Sep 24 14:45 d1
drwxr-xr-x    2 root     root          4096 Sep 24 14:45 d2
drwxr-xr-x    2 root     root          4096 Sep 24 14:46 d3
-rw-rw-r--    1 root     root             3 Sep 24 14:07 nonesuch1

/tmp/d1:
total 0
lrwxrwxrwx    1 root     root            14 Sep 24 14:45 x -> /tmp/nonesuch1

/tmp/d2:
total 0
lrwxrwxrwx    1 root     root            14 Sep 24 14:45 x -> /tmp/nonesuch2

/tmp/d3:
total 4
-rw-rw-r--    1 root     root             3 Sep 24 14:07 x
```

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by edsantiago** [comment]
Don't forget to update `test/system/065-cp.bats`

File: cmd/podman/cp.go [hunk 1]
```diff
@@ -329,6 +329,9 @@ func copy(src, destPath, dest string, idMappingOpts storage.IDMappingOptions, ch
 
 	destfi, err := os.Stat(destPath)
 	if err != nil {
+		if strings.HasSuffix(dest, string(os.PathSeparator)) {
```
Comment (TomSweeneyRedHat) [inline cmd/podman/cp.go]: looks like the same error messge, can you do a single if with an "or" statement?

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 some of the tests aren't too happy.

File: test/system/065-cp.bats [hunk 2]
```diff
@@ -149,7 +149,7 @@ load helpers
     is "$output" "" "output from podman cp 1"
 
     run_podman cp --pause=false $srcdir/$rand_filename2 cpcontainer:/tmp/d2/x/
-    is "$output" "" "output from podman cp 3"
+    is "$output" "Error: failed to get stat of dest path .*stat.* no such file or directory" "cp returns error no such file or directory"
```
Comment (edsantiago) [inline test/system/065-cp.bats]: You need to change the expected exit status, e.g.:
```
run_podman 12345 cp --pause ...
```
...where 12345 is the expected exit status of the cp command (probably 1, but may be something else, see test logs)

Comment (QiWang19) [reply test/system/065-cp.bats]: @edsantiago  thanks. :slightly_smiling_face:  Do I still need keep this current change?

Comment (edsantiago) [reply test/system/065-cp.bats]: The check for "Error"? Yes.

Comment (QiWang19) [reply test/system/065-cp.bats]: :ok

**Comment by QiWang19** [comment]
@TomSweeneyRedHat @edsantiago @mheon PTAL

File: test/system/065-cp.bats [hunk 3]
```diff
@@ -163,8 +163,8 @@ load helpers
 
     # In the second case, podman creates a directory nonesuch2, then
     # creates a file with the same name as the input file. THIS IS WEIRD!
-    run_podman exec cpcontainer cat /tmp/nonesuch2/$rand_filename2
-    is "$output" "$rand_content2" "cp creates destination dir and file"
+    run_podman 1 exec cpcontainer cat /tmp/nonesuch2/$rand_filename2
```
Comment (edsantiago) [inline test/system/065-cp.bats]: Since podman behavior has changed, this is no longer a great test: it simply checks that the destination file doesn't exist - but it is conceivable (albeit improbable) that podman created the destination directory before exiting. That would be very bad. A much better test would now be:
```
# cp into nonexistent directory should not mkdir said directory
run_podman 1 exec cpcontainer test -e /tmp/nonesuch2
```
This test is much more useful.

File: test/system/065-cp.bats [hunk 4]
```diff
@@ -221,4 +221,4 @@ function teardown() {
     basic_teardown
 }
 
-# vim: filetype=sh
+# vim: filetype=sh
```
Comment (edsantiago) [inline test/system/065-cp.bats]: Please fix. (You removed the closing newline. Please add it back).

**Comment by TomSweeneyRedHat** [comment]
Code changes LGTM, I'll let you and @edsantiago work through the testing comments.  Some of the tests aren't happy ATM.

**Comment by edsantiago** [comment]
Latest change (0144c3796ba3dd0555e35fd2cc3f76bde10a90a0) LGTM.

@TomSweeneyRedHat the CI "failures" are the same as yesterday, i.e. false alarms

**Comment by mheon** [comment]
/approve
LGTM

**Comment by QiWang19** [comment]
Needs lgtm label. :label:
