### PR TITLE
fix import not ignoring url path

### LINKED ISSUE #3609: `podman import url` does not work
/kind bug

**Description**
`podman import --help` says 
> Note remote tar balls can be specified, via web address.

but this appears not to work.

**Steps to reproduce the issue:**

1. `podman import http://kojipkgs.fedoraproject.org/packages/Fedora-Container-Base/Rawhide/20190719.n.1/images/Fedora-Container-Base-Rawhide-20190719.n.1.x86_64.tar.xz`

**Describe the results you received:**
```
Error: invalid filename (should not contain ':') "http://kojipkgs.fedoraproject.org/packages/Fedora-Container-Base/Rawhide/20190719.n.1/images/Fedora-Container-Base-Rawhide-20190719.n.1.x86_64.tar.xz"
```
(Omitting `http://` gives a different error)

**Describe the results you expected:**

No error

**Output of `podman version`:**
```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**
```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.0.0-dev, commit: 164df8af4e62dc759c312eab4b97ea9fb6b5f1fc'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 1687924736
  MemTotal: 16450478080
  OCIRuntime:
    package: runc-1.0.0-93.dev.gitb9b6cc6.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8+dev
      commit: e3b4c1108f7d1bf0d09ab612ea09927d9b59b4e3
      spec: 1.0.1-dev
  SwapFree: 8296329216
  SwapTotal: 8296329216
  arch: amd64
  cpus: 8
  hostname: localhost.localdomain
  kernel: 5.1.18-300.fc30.x86_64
  os: linux
  rootless: true
  uptime: 6h 18m 0.13s (Approximately 0.25 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/petersen/.config/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/petersen/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 20
  RunRoot: /run/user/1000
  VolumePath: /var/home/petersen/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora Silverblue 30

### PR DESCRIPTION
**Pull request by QiWang19**
fix #3609
 This PR allows the program to continue if the input is a valid URL.
Podman import used to check filename to only allow tarball path as a file. It should also allow an URL as the doc mentioned.

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by QiWang19** [comment]
Can I find the URL of image tarball to add test for this?

**Comment by rhatdan** [comment]
Can you do
file://localhost/Path/to/tar?

**Comment by QiWang19** [comment]
No runtime_img.go `downloadFromURL` doesn't support this.  `Get file:///home/qiwan/Documents/img.tar: unsupported protocol scheme "file"`

**Comment by QiWang19** [comment]
@TomSweeneyRedHat @mheon @haircommander PTAL

File: cmd/podman/shared/parse/parse.go [hunk 1]
```diff
@@ -162,3 +163,9 @@ func ValidateFileName(filename string) error {
 	}
 	return nil
 }
+
+// ValidURL checks a string urlStr is a url or not
+func ValidURL(urlStr string) error {
+	_, err := url.ParseRequestURI(urlStr)
+	return errors.Wrapf(err, "invalid url path: %q", urlStr)
```
Comment (haircommander) [inline cmd/podman/shared/parse/parse.go]: it seems to me that doing this wrapping mean ValidURL always returns error, regardless of if the url is valid?

Comment (QiWang19) [reply cmd/podman/shared/parse/parse.go]: yes, I forget to change when I wrap the error

Comment (QiWang19) [reply cmd/podman/shared/parse/parse.go]: but yes passing a nil err to wrapf return nil

**Comment by haircommander** [comment]
LGTM

**Comment by mheon** [comment]
Code LGTM

File: cmd/podman/import.go [hunk 2]
```diff
@@ -69,8 +69,11 @@ func importCmd(c *cliconfig.ImportValues) error {
 		return errors.Errorf("too many arguments. Usage TARBALL [REFERENCE]")
 	}
 
-	if err := parse.ValidateFileName(source); err != nil {
-		return err
+	errFileName := parse.ValidateFileName(source)
+	errURL := parse.ValidURL(source)
+
+	if errFileName != nil && errURL != nil {
+		return errors.Errorf("%q, %q invalid tarball path", errFileName, errURL)
```
Comment (mheon) [inline cmd/podman/import.go]: We could use a multierror here, maybe?

Comment (mheon) [reply cmd/podman/import.go]: https://github.com/hashicorp/go-multierror

Comment (QiWang19) [reply cmd/podman/import.go]: :ok_hand: I'm looking

**Comment by mheon** [comment]
@QiWang19 Not sure what these test failures are, but I don't think they're you - mind rebasing+repushing?

**Comment by QiWang19** [comment]
@mheon PTAL

**Comment by mheon** [comment]
LGTM
@rhatdan @TomSweeneyRedHat @vrothberg @giuseppe @baude PTAL
