### PR TITLE
podman import syntax fix

### LINKED ISSUE #4000: `import -c 'CMD...'` behavior does not match
/kind bug

**Description**

comparing the behavior of docker-1.13.1 with podman 1.2.0, the `podman import -c 'CMD..' ...` behaviour does not match back.
podman is expecting `'CMD=/usr/bin/farts'` (the '='), and fails with `'CMD /usr/bin/farts'` (the ' '), and fails with brackets `'CMD ["/usr/bin/farts"]'`.

```bash
[vbatts@knob] {master} ~$ podman import -c 'CMD ["/usr/bin/farts"]' ./farts.tar vbatts/farts
Error: invalid argument "CMD [\"/usr/bin/farts\"]" for "-c, --change" flag: parse error on line 1, column 5: bare " in non-quoted-field
[vbatts@knob] {master} ~$ podman import -c 'CMD /usr/bin/farts' ./farts.tar vbatts/farts
Error: error adding config changes to image "./farts.tar": no value given for instruction "CMD /usr/bin/farts"
[vbatts@knob] {master} ~$ podman import -c 'CMD=/usr/bin/farts' ./farts.tar vbatts/farts
Getting image source signatures
Copying blob 7a230c035746 done
Copying config 66c42e9891 done
Writing manifest to image destination
Storing signatures
66c42e989172c9294213dda7ec4917d285ce6f646f0972b3e4eb7605a65b9dc1
```

whereas docker-1.13.1 supports ' ' and brackets, but fails with '='.

```bash
[vbatts@beats] {master} ~$ docker import -c 'CMD=/usr/bin/farts' ./farts.tar vbatts/farts
Error response from daemon: cmd=/usr/bin/farts is not a valid change command
[vbatts@beats] {master} ~$ docker import -c 'CMD ["/usr/bin/farts"]' ./farts.tar vbatts/farts
sha256:19b84065571402b7844b8866d4cd9d7babf86d350da23338c64ea96446f36b56
[vbatts@beats] {master} ~$ docker import -c 'CMD /usr/bin/farts' ./farts.tar vbatts/farts
sha256:7d6d0a14238fa4ce51c5138537acb95d8c20a6a9f8b54753382a301e00ba59f6
```

**Output of `podman version`:**

```
Version:            1.2.0
RemoteAPI Version:  1
Go Version:         go1.11.5
Git Commit:         3bd528e583182b4249f3e6bbd8497a8831d89950
Built:              Tue Apr  2 09:59:40 2019
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.5.1-3.fc29.x86_64
```

### PR DESCRIPTION
**Pull request by kunalkushwaha**
syntax updated for podman import --change
    
currently, podman import change do not support syntax like
- KEY val
- KEY ["val"]
This adds support for both of these syntax along with KEY=val
Fixes #4000     

Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>

### CODE REVIEW

**Comment by kunalkushwaha** [comment]
Updated the PR with changes. 
CMD and Entrypoints both supports string array as expected with this update.

File: pkg/util/utils.go [hunk 1]
```diff
@@ -69,6 +69,29 @@ func StringInSlice(s string, sl []string) bool {
...
 
+// ParseChanges returns key, value pair for given option.
+func ParseChanges(option string) []string {
+	// Supported format as below
+	// key=value
+	// key value
+	// key ["value"]
+	var keyValPair []string
+	var val string
+	if strings.Contains(option, "=") {
```
[the remark this answers is not in the document]
Comment (kunalkushwaha) [reply pkg/util/utils.go]: updated code supports this now.

File: cmd/podman/import.go [hunk 2]
```diff
@@ -39,7 +39,7 @@ func init() {
 	importCommand.SetHelpTemplate(HelpTemplate())
 	importCommand.SetUsageTemplate(UsageTemplate())
 	flags := importCommand.Flags()
-	flags.StringSliceVarP(&importCommand.Change, "change", "c", []string{}, "Apply the following possible instructions to the created image (default []): CMD | ENTRYPOINT | ENV | EXPOSE | LABEL | STOPSIGNAL | USER | VOLUME | WORKDIR")
+	flags.StringArrayVarP(&importCommand.Change, "change", "c", []string{}, "Apply the following possible instructions to the created image (default []): CMD | ENTRYPOINT | ENV | EXPOSE | LABEL | STOPSIGNAL | USER | VOLUME | WORKDIR")
```
Comment (kunalkushwaha) [inline cmd/podman/import.go]: This was required as `StringSlice*`  functions treat `,` as delimiter.

File: pkg/util/utils.go [hunk 3]
```diff
@@ -69,6 +69,32 @@ func StringInSlice(s string, sl []string) bool {
...
+		key = strings.Trim(tokens[0], " ") // Need to trim whitespace part of delimeter.
+		val = tokens[1]
+		if strings.Contains(tokens[1], "[") {
+			//Trim '[',']' if exist.
+			val = strings.TrimLeft(strings.TrimRight(tokens[1], "]"), "[")
+		}
+		vals = strings.Split(val, ",")
+	} else if strings.Contains(option, "=") {
+		// handles condition 1.
+		tokens := strings.Split(option, "=")
```
Comment (mheon) [inline pkg/util/utils.go]: `SplitN(option, "=", 2)` probably safer

File: pkg/util/utils.go [hunk 4]
```diff
@@ -87,40 +113,41 @@ func GetImageConfig(changes []string) (v1.ImageConfig, error) {
...
 			var st struct{}
-			volumes[pair[1]] = st
+			volumes[vals[0]] = st
 		case "WORKDIR":
-			workingDir = pair[1]
+			workingDir = vals[0]
 		case "LABEL":
-			if len(pair) == 3 {
-				labels[pair[1]] = pair[2]
+			if len(vals) == 3 {
```
Comment (mheon) [inline pkg/util/utils.go]: This looks... questionable? Should't this be len(vals) == 2?

File: pkg/util/utils.go [hunk 5]
```diff
@@ -87,40 +113,41 @@ func GetImageConfig(changes []string) (v1.ImageConfig, error) {
...
-			user = pair[1]
+			user = vals[0]
 		case "EXPOSE":
 			var st struct{}
-			exposedPorts[pair[1]] = st
+			exposedPorts[vals[0]] = st
 		case "ENV":
-			if len(pair) < 3 {
-				return v1.ImageConfig{}, errors.Errorf("no value given for environment variable %q", pair[1])
+			if len(vals) < 3 {
```
Comment (mheon) [inline pkg/util/utils.go]: This also looks like it ought to be 2 instead of 3

File: pkg/util/utils.go (hunk 3 above)
Comment (kunalkushwaha) [reply pkg/util/utils.go]: In case of parameters like ``KEY=Opt=val2``, This will not work or we need one more split.

**Comment by kunalkushwaha** [comment]
Not sure, why these tests failing. 126 is expected output and it seems it is returning also 126.
Also these test are not related to added test or code.

``` 
[+1057s] [Fail] Podman run exit [It] podman run exit 126 
[+1057s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_exit_test.go:46
[+1057s] 
[+1057s] [Fail] Podman run exit [It] podman run exit 126 
[+1057s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_exit_test.go:46
[+1057s] 
[+1057s] [Fail] Podman run exit [It] podman run exit 126 
[+1057s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_exit_test.go:46
[+1057s] 
[+1057s] [Fail] Podman run [It] podman run exit code on failure to exec 
[+1057s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_test.go:633
[+1057s] 
[+1057s] [Fail] Podman run [It] podman run exit code on failure to exec 
[+1057s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/run_test.go:633
```

**Comment by rhatdan** [comment]
Did you rebase and push?

**Comment by mheon** [comment]
Yeah, those look like flakes we fixed upstream

**Comment by kunalkushwaha** [comment]
I re-run the test, I guess that results into all green :)

**Comment by rhatdan** [comment]
Thanks @kunalkushwaha LGTM
@mheon @vrothberg @giuseppe @baude @jwhonce @QiWang19 PTAL

**Comment by TomSweeneyRedHat** [comment]
Could we get an example or two added to the man page?

File: pkg/util/utils.go [hunk 6]
```diff
@@ -69,6 +69,32 @@ func StringInSlice(s string, sl []string) bool {
 	return false
 }
 
+// ParseChanges returns key, value(s) pair for given option.
+func ParseChanges(option string) (key string, vals []string) {
```
Comment (vrothberg) [inline pkg/util/utils.go]: Can we add unit tests for it? Parts of it is already tested in the integration but we should throw more input at it. We've regressed several times on parsing functions, so I prefer to have some extra security net.

Comment (vrothberg) [reply pkg/util/utils.go]: Thanks for the great comments all around the code!

File: pkg/util/utils.go [hunk 7]
```diff
@@ -69,6 +69,32 @@ func StringInSlice(s string, sl []string) bool {
...
+	// Supported format as below
+	// 1. key=value
+	// 2. key value
+	// 3. key ["value","value1"]
```
Comment (vrothberg) [inline pkg/util/utils.go]: I prefer using a regex which is less prone to errors than a manual parsing approach. Especially the limitation of not allowing whitespaces between items (see case 3) is something we can easily support with regexes but is hard to get right manually.

Comment (vrothberg) [reply pkg/util/utils.go]: I looked into a regex for case 3) and came up with `(?:\[?"([^"]+)"\s*,?\s*\]?)`. Note that it only parses the value/list and not the key.

A go example with this regex: https://play.golang.org/p/o43IB2hIQXh

Comment (rhatdan) [reply pkg/util/utils.go]: Can we do the regex fix in a different PR.  I would like to get this in before the release.

**Comment by rhatdan** [comment]
LGTM

File: pkg/util/utils.go (hunk 7 above)
Comment (vrothberg) [reply pkg/util/utils.go]: I am okay with adding a regex after the PR but we need more tests for it. Currently, we require specific input formats but don't return errors if the input is malformed. I don't want to merge before that's addressed.

If we consider this PR as bug fix, it can easily get into 1.6.1.

Comment (kunalkushwaha) [reply pkg/util/utils.go]: I am trying to comeup with regex, but it will agin be mix of manual parsing + regex as each 3 use case are different.(I am not regex expert).

It will be nice, if we can add regex in next PR.

Comment (vrothberg) [reply pkg/util/utils.go]: @kunalkushwaha, thanks. Yes, let's add regexes later but I really want the function to return an error if the input does not have the required format.

Comment (kunalkushwaha) [reply pkg/util/utils.go]: I will check each string for validity + brackets

Comment (kunalkushwaha) [reply pkg/util/utils.go]: @vrothberg PTAL

**Comment by kunalkushwaha** [comment]
Hi @vrothberg  I have added unit test for `ParseChages`.  PTAL

File: pkg/util/utils.go [hunk 8]
```diff
@@ -69,6 +70,50 @@ func StringInSlice(s string, sl []string) bool {
...
+		vals = strings.Split(val, ",")
+	} else if strings.Contains(option, "=") {
+		// handles condition 1.
+		tokens := strings.Split(option, "=")
+		key = tokens[0]
+		vals = tokens[1:]
+	} else {
+		// either ` ` or `=` must be provided after command
+		return "", []string{}, fmt.Errorf("invalid format %s", option)
+	}
```
Comment (TomSweeneyRedHat) [inline pkg/util/utils.go]: What happens if someone puts in `--change LABEL = blue=image`  ?

File: pkg/util/utils_test.go [hunk 9]
```diff
@@ -17,3 +18,45 @@ func TestStringInSlice(t *testing.T) {
...
+	assert.Equal(t, `invalid value "/bin /sh"`, err.Error())
+
+	// CMD?
+	_, _, err = ParseChanges(`CMD?`)
+	assert.Equal(t, `invalid format CMD?`, err.Error())
+
+	// empty values for CMD
+	_, _, err = ParseChanges(`CMD `)
+	assert.Equal(t, `invalid value `, err.Error())
+
```
Comment (TomSweeneyRedHat) [inline pkg/util/utils_test.go]: Would be nice to have a test for `--change LABEL=blue=image` here and probably my question case `--change LABEL = blue=image`

File: pkg/util/utils.go (hunk 8 above)
Comment (kunalkushwaha) [reply pkg/util/utils.go]: with current logic, it will be an error case. Though we can remove whitespaces in this condition.
Please let me know WDYT.

File: pkg/util/utils_test.go (hunk 9 above)
Comment (kunalkushwaha) [reply pkg/util/utils_test.go]: I added the testcase for this.

File: pkg/util/utils_test.go [hunk 10]
```diff
@@ -17,3 +18,54 @@ func TestStringInSlice(t *testing.T) {
...
+	assert.EqualValues(t, []string{"/bin/sh"}, vals)
+	assert.NoError(t, err)
+
+	// CMD ["/bin/sh"]
+	_, vals, err = ParseChanges(`CMD ["/bin/sh"]`)
+	assert.EqualValues(t, []string{`"/bin/sh"`}, vals)
+	assert.NoError(t, err)
+
+	// CMD ["/bin/sh", "-c", "ls"]
+	_, vals, err = ParseChanges(`CMD ["/bin/sh","c","ls"]`)
```
Comment (vrothberg) [inline pkg/util/utils_test.go]: Can we add tests with spaces between items `["a", "b"]` and others with a commas in the strings `["/bin/foo", "--string-arg", "' some sentence\, with a comma'"]`?

Comment (kunalkushwaha) [reply pkg/util/utils_test.go]: comma is not checked for invalid value

**Comment by kunalkushwaha** [comment]
have added these testcases.

I think `parseChanges()` works as expected as of now. Though It can be improved with various implementations and we can do it in next PR as discussed earlier. We can add more testcases too along with that. 
I would request to merge this PR if no serious issues pending against it.

**Comment by rhatdan** [comment]
Lets get this merged, waiting for @vrothberg approval.

**Comment by vrothberg** [comment]
@rhatdan @baude @mheon @TomSweeneyRedHat PTAL

Note that the parsing is not yet 100 percent accurate (see an example below) but a huge improvement over the current state. 
```go
// CMD ["/bin/sh","arg-with,comma"]
_, vals, err = ParseChanges(`CMD ["/bin/sh","arg-with,comma"]`)
assert.EqualValues(t, []string{`"/bin/sh"`, `"arg-with`, `comma"`}, vals)
assert.NoError(t, err)
```

File: pkg/util/utils.go (hunk 8 above)
Comment (TomSweeneyRedHat) [reply pkg/util/utils.go]: error, condition works for me @kunalkushwaha , thanks!

**Comment by TomSweeneyRedHat** [comment]
LGTM, but would like @mheon to take one more look before merging.
