### PR TITLE
images --format compatible with docker

### LINKED ISSUE #5110: podman images --format incompatibility with docker
/kind bug

**Description**

The tags available in the `podman images --format` option is incompatible with docker. In particular, docker has both `{{.CreatedAt}}` and `{{.CreatedSince}}` while podman has neither but has `{{.Created}}` instead.

**Steps to reproduce the issue:**

1. `docker images --format '{{.CreatedAt}}'`

2. `podman images --format '{{.CreatedAt}}'`

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.12.13
Git Commit:         b7ce1157b00af09f4a09e39b377aa3abff46ee05
Built:              Sun Jan 19 14:08:07 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: b7ce1157b00af09f4a09e39b377aa3abff46ee05
  go version: go1.12.13
  podman version: 1.7.0
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.10, commit: 7a830be343876ac381c965c7429a7fb9b3d7a609'
  Distribution:
    distribution: gentoo
    version: unknown
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 500
      size: 1
    - container_id: 1
      host_id: 1000000
      size: 100000
    uidmap:
    - container_id: 0
      host_id: 500
      size: 1
    - container_id: 1
      host_id: 1000000
      size: 100000
  MemFree: 2903642112
  MemTotal: 33604526080
  OCIRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc9
      spec: 1.0.1-dev
  SwapFree: 2019291136
  SwapTotal: 2147479552
  arch: amd64
  cpus: 12
  eventlogger: journald
  hostname: lorien
  kernel: 5.4.15
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: Unknown
    Version: |-
      slirp4netns version 0.4.2
      commit: 69153b0d1cb82216d6782179ff7c3c5e91c731a1
  uptime: 214h 10m 6.52s (Approximately 8.92 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /home/bruce/.config/containers/storage.conf
  ContainerStore:
    number: 5
  GraphDriverName: btrfs
  GraphOptions: {}
  GraphRoot: /scratch/containers/storage
  GraphStatus:
    Build Version: 'Btrfs v5.4.1 '
    Library Version: "102"
  ImageStore:
    number: 27
  RunRoot: /tmp/500
  VolumePath: /scratch/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
app-emulation/libpod-1.7.0::gentoo  USE="btrfs rootless -apparmor (-selinux) (-ostree%)"
```

### PR DESCRIPTION
**Pull request by QiWang19**
Let valid values of --format be compatible with docker. Replace CreatedTime with CreatedAt, Created with CreatedSince.
fix #5110 

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
LGTM but would prefer to hold until after 1.8.0 so I don't need to update release notes again

**Comment by QiWang19** [comment]
> Any man page changes? Tests?
> Also can I still use the old values? If I built a script using Created or CreatedTime, will it still work?

We can add man pages like this https://docs.docker.com/engine/reference/commandline/images/#format-the-output
old value `--format {{.Created}}` won't work. Should be `{{.CreatedSince}}` now

**Comment by TomSweeneyRedHat** [comment]
Looks like the same test errors here as in some other PRs.  Houston we may have a CI problem.

File: cmd/podman/images.go [hunk 1]
```diff
@@ -21,16 +21,16 @@ import (
...
+	Repository   string
+	Tag          string
+	ID           string
+	Digest       digest.Digest
+	Digests      []digest.Digest
+	CreatedAt    time.Time
+	CreatedSince string
+	Size         string
+	ReadOnly     bool
+	History      string
```
Comment (TomSweeneyRedHat) [inline cmd/podman/images.go]: Just wondering if we should still support "Created" and "CreatedTime" in case people have adjusted and have built dependencies on those?  I'd be fine if they were hidden options going forward, available for use, but not documented.

**Comment by TomSweeneyRedHat** [comment]
definitely double check on the man pages and tests.  If we do drop the old names, we will need a BIG announcement in the 1.8.1 or 1.9.0 Release announcement about that.

File: cmd/podman/images.go (hunk 1 above)
Comment (QiWang19) [reply cmd/podman/images.go]: My concern is that keeping `Created` and `CreatedTime` in this struct for hidden options seems duplicate.

Comment (TomSweeneyRedHat) [reply cmd/podman/images.go]: yep, it's certainly a duplicate and I'd add a comment in the code as to why it's there.  My concern is someone out there has already built a dependency on one of those and we might break them if they go away.

Comment (mheon) [reply cmd/podman/images.go]: I would not retain duplicates in the structures - especially given how similar all these names are. We may want to look into normalization similar to what we're doing in `podman inspect --format` though.

Comment (QiWang19) [reply cmd/podman/images.go]: @TomSweeneyRedHat @mheon Thanks. I will do that.

Comment (TomSweeneyRedHat) [reply cmd/podman/images.go]: If Matt's hip, then I'm hip.  Thanks for the discussion!

**Comment by rhatdan** [comment]
LGTM
But not sure what is happening with the remote tests.
