### PR TITLE
Podman-remote usage message to display `podman-remote` instead of `podman`

### LINKED ISSUE #3503: podman-remote:  messages refer to `podman` instead of `podman-remote`
Examples:
```
[~]$ podman-remote
Error: missing command 'podman COMMAND'
Try 'podman --help' for more information.

[~]$ podman-remote awoeuerwr
Error: unrecognized command `podman awoeuerwr`
Try 'podman --help' for more information.

[~]$ podman-remote --help | tail -n1
Use "podman [command] --help" for more information about a command.
```

One way to approach this, could be to make the root-cobra-command build conditional. This would allow for changing the description as well.

Cc: @baude @jwhonce

### PR DESCRIPTION
**Pull request by ashley-cui**
When the user uses remote client, the message prompts the user to use `podman-remote`. This does not apply for Mac usage.

Closes #3503

Signed-off-by: Ashley Cui <ashleycui16@gmail.com>

### CODE REVIEW

**Comment by ashley-cui** [comment]
@vrothberg PTAL

**Comment by mheon** [comment]
/approve

This one tentatively LGTM but someone more familiar with makefile stuff should review this

File: cmd/podman/main.go [hunk 1]
```diff
@@ -67,8 +67,10 @@ var mainCommands = []*cobra.Command{
 	systemCommand.Command,
 }
 
+var cmdUsage = "podman"
+
 var rootCmd = &cobra.Command{
-	Use:  "podman",
+	Use:  cmdUsage,
```
Comment (rhatdan) [inline cmd/podman/main.go]: Why not set this to 
path.Base(os.Args[0])

Then you don't need to change anything else.

Comment (ashley-cui) [reply cmd/podman/main.go]: Good idea, done.

Comment (rhatdan) [reply cmd/podman/main.go]: path.Base(os.Executable()) might be cleaner.

**Comment by rhatdan** [comment]
Actually I think we can go with this.
/lgtm
