### PR TITLE
fix security-opt generate kube

### LINKED ISSUE #4950: generate kube does not include security-opt
/kind bug

**Description**

The `security-opt` is not included when generated kubernetes pod descriptions.

**Steps to reproduce the issue:**

```
podman run --name test -v `pwd`:/host --security-opt "label=disable" docker.io/library/bash:latest ls /host
podman generate kube > test.yaml
```

**Describe the results you received:**
The `security-opt` has no influence on the generated yaml

**Describe the results you expected:**
the `test.yaml` should contain `securityContext: seLinuxOptions`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.7.0-2.fc31.x86_64
```

### PR DESCRIPTION
**Pull request by QiWang19**
fix #4950
add selinux options from --security-opt from the container to generate kube result

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

File: libpod/kube.go [hunk 1]
```diff
@@ -468,11 +468,28 @@ func generateKubeSecurityContext(c *Container) (*v1.SecurityContext, error) {
...
+		case "user":
+			selinuxOpts.User = opts[1]
+		case "role":
+			selinuxOpts.Role = opts[1]
+		case "type":
+			selinuxOpts.Type = opts[1]
+		case "level":
+			selinuxOpts.Level = opts[1]
+		default:
+			return nil, errors.Errorf("unknown field of SELinuxOptions: %s", opts[0])
```
Comment (mheon) [inline libpod/kube.go]: Should be a `errors.Wrapf(define.ErrInternal, ...`

File: libpod/kube.go [hunk 2]
```diff
@@ -468,11 +468,28 @@ func generateKubeSecurityContext(c *Container) (*v1.SecurityContext, error) {
 		return nil, err
 	}
 
+	var selinuxOpts v1.SELinuxOptions
+	opts := strings.SplitN(c.config.Spec.Annotations[InspectAnnotationLabel], ":", 2)
+	if len(opts) == 2 {
+		switch opts[0] {
```
Comment (mheon) [inline libpod/kube.go]: I'm 99% sure that this is going to be set to `disabled` in almost every use, so we need to support that

File: libpod/kube.go (hunk 1 above)
Comment (mheon) [reply libpod/kube.go]: We are also missing `filesystem` support, I think.

Comment (mheon) [reply libpod/kube.go]: Oh, sorry, that second comment should go with the one above

File: libpod/kube.go (hunk 2 above)
Comment (QiWang19) [reply libpod/kube.go]: what should we do here if it's `disable`?

Comment (mheon) [reply libpod/kube.go]: That's an excellent question... Can Kube YAML not request SELinux be turned off? @rhatdan

Comment (haircommander) [reply libpod/kube.go]: I actually don't think it can on the kube yaml level. I am pretty sure the only way to disable selinux in a pod is to give it privilege

Comment (haircommander) [reply libpod/kube.go]: here's the object definition: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#selinuxoptions-v1-core, and per: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podsecuritycontext-v1-core if one isn't specified the runtime allocates one (if it's privileged it's given spc_t, which effectively disables)

File: libpod/kube.go (hunk 1 above)
Comment (QiWang19) [reply libpod/kube.go]: > We are also missing `filesystem` support, I think.


the fstype is not defined under v1.SELinuxOptions, should it be supported somewhere else?

File: libpod/kube.go (hunk 2 above)
Comment (QiWang19) [reply libpod/kube.go]: can it be hardcoded `selinuxOpts.Type = "spec_t"` to type:spc_t?

Comment (haircommander) [reply libpod/kube.go]: yeah that can be done

File: libpod/kube.go (hunk 1 above)
Comment (mheon) [reply libpod/kube.go]: I'm not sure, but we have to support it somehow - otherwise we'll break `generate kube` on containers with it set

**Comment by rhatdan** [comment]
Kube.yaml supports type not disabled.  
```
podman --security-opt label:disable 
```
means
kube.yaml
```
security_opt:
     type spc_t
```

**Comment by QiWang19** [comment]
@mheon @haircommander @rhatdan PTAL

**Comment by haircommander** [comment]
LGTM

**Comment by rhatdan** [comment]
@FlorianLudwig PTAL
