### PR TITLE
fix bug convert volume host path to absolute

### LINKED ISSUE #3504: Volume mount of '.' uses internal directory
/kind bug

When using `.` as the source of a volume mount podman seems to use a podman related directory for the mount instead of either using the current directory or throwing an error.

**Steps to reproduce the issue:**

```
$ podman run --rm -v .:/test -it alpine
/ # ls -la /test/
total 36
drwx------    4 root     root          4096 Jul  6 10:18 .
drwxr-xr-x    1 root     root          4096 Jul  6 10:18 ..
drwxr-xr-x    2 root     root          4096 Jul  6 10:18 artifacts
srwx------    1 root     root             0 Jul  6 10:18 attach
-rw-r--r--    1 root     root         20428 Jul  6 10:18 config.json
prw-r--r--    1 root     root             0 Jul  6 10:18 ctl
-rw-------    1 root     root           735 Jul  6 10:18 ctr.log
drwxrwxrwt    2 root     root            40 Jul  6 10:18 shm
/ #
```

**Output of `podman version`:**

```
Version:            1.4.3
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.4.3
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 3911909376
  MemTotal: 16775352320
  OCIRuntime:
    package: 'cri-o-runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 8
  hostname: computator
  kernel: 4.15.0-54-generic
  os: linux
  rootless: true
  uptime: 5h 46m 46.17s (Approximately 0.21 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
store:
  ConfigFile: /home/user/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /home/user/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /run/user/1000
  VolumePath: /home/user/.local/share/containers/storage/volumes
```

### PR DESCRIPTION
**Pull request by QiWang19**
fix #3504 If --volume host:dest host is not a named volume, convert the host to a absolute directory path.

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

File: pkg/spec/storage.go [hunk 1]
```diff
@@ -663,6 +664,12 @@ func (config *CreateConfig) getVolumeMounts() (map[string]spec.Mount, map[string
 
 		if strings.HasPrefix(src, "/") || strings.HasPrefix(src, ".") {
 			// This is not a named volume
+			// convert src to an absolute path
+			src, err := filepath.Abs(src)
+			log.Println("src is , ", src)
```
Comment (rhatdan) [inline pkg/spec/storage.go]: This looks like debugging information.

File: pkg/spec/storage.go [hunk 2]
```diff
@@ -663,6 +664,12 @@ func (config *CreateConfig) getVolumeMounts() (map[string]spec.Mount, map[string
...
+			if err != nil {
+				return nil, nil, errors.Wrapf(err, "error getting absolute source path")
```
Comment (rhatdan) [inline pkg/spec/storage.go]: Could you wrap include the `src` directory.

File: pkg/spec/storage.go (hunk 1 above)
Comment (rhatdan) [reply pkg/spec/storage.go]: Can you use `source` as the new variable, so we can refer back to src.

File: pkg/spec/storage.go [hunk 3]
```diff
@@ -663,10 +663,15 @@ func (config *CreateConfig) getVolumeMounts() (map[string]spec.Mount, map[string
 
 		if strings.HasPrefix(src, "/") || strings.HasPrefix(src, ".") {
 			// This is not a named volume
+			// convert src to an absolute path
+			source, err := filepath.Abs(src)
```
Comment (mheon) [inline pkg/spec/storage.go]: This is a bad place to handle things since it only hits the `--volume` flag and not `--mount`. Better place would be the loop at https://github.com/containers/libpod/blob/943c8daf6db1ec9995f0e7a8f1392c2d83dc4376/pkg/spec/storage.go#L203-L214 - after we check for tmpfs, check if it's a bind mount, and if it is do a filepath.Abs() on the source path.

**Comment by mheon** [comment]
/approve
Change LGTM

**Comment by mheon** [comment]
Needs rebase to fix tests

**Comment by QiWang19** [comment]
@mheon rebased, PTAL

**Comment by mheon** [comment]
LGTM on my end. @vrothberg @giuseppe @rhatdan PTAL
