### PR TITLE
fix login supports credHelpers config

### LINKED ISSUE #1675: podman login should use credential helper if configured
`docker login' uses a credential helper.  If you try to do `docker login` without a credential helper in play you get a warning:

```
# docker login https://quay.io
Username: tomsweeneyredhat
Password:
WARNING! Your password will be stored unencrypted in
/root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

`podman login` should also use a credential helper as Docker does.

### PR DESCRIPTION
**Pull request by QiWang19**
Skip the error if login can't find credentials in credHelpers with credHelpers configured in auth.json and podman login will store the new credentials to credHelpers later.
close #1675 
Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

File: cmd/podman/login.go [hunk 1]
```diff
@@ -90,7 +91,8 @@ func loginCmd(c *cliconfig.LoginValues) error {
 
 	// username of user logged in to server (if one exists)
 	userFromAuthFile, passFromAuthFile, err := config.GetAuthentication(sc, server)
-	if err != nil {
+	// Do not return error if no credentials found in credHelpers, new credentials will be stored by config.SetAuthentication
+	if err != nil && err != credentials.NewErrCredentialsNotFound() {
```
Comment (mheon) [inline cmd/podman/login.go]: Should be errors.Cause(err) instead of err, to be safe (we might wrap the error at some later point)?

Comment (QiWang19) [reply cmd/podman/login.go]: this err is not wrapped in `config.GetAuthentication` -> `findAuthentication(registry, path, legacyFormat)`. 
you mean wrap it in `config.GetAuthentication` and use errors.Cause(err) here?
