### PR TITLE
libpod/container_internal: Split locale at the first dot, etc.

### LINKED ISSUE #2494: language: tag is not well-formed
/kind bug

**Description**
Warning about a not-wellformed tag when parsing language.

**Steps to reproduce the issue:**
`podman --log-level debug run -it --rm --read-only busybox sh`

**Describe the results you received:**
`WARN[0000] failed to parse language "en_US.UTF-8": language: tag is not well-formed`

**Describe the results you expected:**
No warning :)

**Additional information you deem important (e.g. issue happens only occasionally):**
```
# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Output of `podman version`:**
```
podman version 1.2.0-dev
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: 91373151335a84c5b78dbe46362cb678807d7509
  go version: go1.11.5
  podman version: 1.2.0-dev
host:
  BuildahVersion: 1.7.1
  Conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.14.0-dev, commit: 8de2ffc9e0809e98a72b93e35b74b8e5d4b0c29c'
  Distribution:
    distribution: debian
    version: "9"
  MemFree: 32108892160
  MemTotal: 38205562880
  OCIRuntime:
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: f79e211b1d5763d25fb8debda70a764ca86a0f23
      spec: 1.0.1-dev
  SwapFree: 8586784768
  SwapTotal: 8586784768
  arch: amd64
  cpus: 8
  hostname: pgsql
  kernel: 4.19.0-0.bpo.2-amd64
  os: linux
  rootless: false
  uptime: 26h 48m 2.64s (Approximately 1.08 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox 6 on Windows 10, running Debian 9 (stable)

### PR DESCRIPTION
**Pull request by wking**
We're going to feed this into Go's BCP 47 language parser.  [Language tags have the form][1]:

```abnf
langtag = language
          ["-" script]
          ["-" region]
          *("-" variant)
          *("-" extension)
          ["-" privateuse]
```

and [locales have the form][2]:

    [language[_territory][.codeset][@modifier]]

The modifier is useful for collation, but Go's language-based API (golang/go#25340) does not provide a way for us to supply it.  This code converts our locale to a BCP 47 language by stripping the dot and later and replacing the first underscore, if any, with a hyphen.  This will avoid errors like #2494:

    WARN[0000] failed to parse language "en_US.UTF-8": language: tag is not well-formed

when feeding `language.Parse(...)`.

CC @mtrmac.  While #2501 is hashing out whether or not to keep locale-based collation, I thought I might as well fix the bug in the current implementation ;).

Fixes #2494.

[1]: https://tools.ietf.org/html/bcp47#section-2.1
[2]: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_02

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mheon** [comment]
/approve
Code LGTM

File: libpod/container_internal.go [hunk 1]
```diff
@@ -1281,6 +1281,16 @@ func (c *Container) saveSpec(spec *spec.Spec) error {
 	return nil
 }
 
+// localeToLanguage translates POSIX locale strings to BCP 47 language tags.
+func localeToLanguage(locale string) string {
+	locale = strings.Replace(strings.SplitN(locale, ".", 2)[0], "_", "-", 1)
```
Comment (mtrmac) [inline libpod/container_internal.go]: (Absolutely non-blocking: This would benefit from a comment, at least saying what is the discarded part supposed to be. OTOH there are tests, so there is enough documentation in that sense.)

**Comment by mheon** [comment]
I think we're good to merge here - it definitely fixes the warning for common locales.
/lgtm

**Comment by mheon** [comment]
Alright, what happened here? Did the bot ignore the yellow tests?

**Comment by wking** [comment]
> Alright, what happened here? Did the bot ignore the yellow tests?

What yellow tests?  And Tide might only respect Prow tests, I'm not sure.

**Comment by mheon** [comment]
I'd just restarted a failing test that usually takes around 40 minutes to pass... I think it didn't register that and merged anyways.
