### PR TITLE
podman copy  files to the volume with a container

### LINKED ISSUE #3059: podman cp: not working with volumes
(where "not working" means "files seem to vanish")
```
# podman volume create v
v
# podman run -d --name foo -v v:/mydir alpine sleep 600
b23df78e6fe60da7328cc34a5f1ebf0315075348b11c88010bffcb233c3b787e
# vdir=$(podman volume inspect -f '{{.MountPoint}}' v)
# ls -l $vdir
total 0
```
So far, so good. Now create a file, try to cp it into the volume in the container:
```
# echo hi >myfile
# podman cp myfile foo:/mydir/myfile_in_v
# ls -l $vdir
total 0
# podman exec foo ls -la /mydir
total 12
drwxr-xr-x    2 root     root          4096 May  2 17:19 .
drwxr-xr-x    1 root     root          4096 May  2 17:19 ..
```
That is: the 'cp' seemed to be a NOP. Running `find / -name 'my*'` in the container does not locate the desired myfile.

Or, create a file in the volume, try to cp it out:
```
# echo i am in the volume >$vdir/file_in_vdir
# podman exec foo ls -l /mydir
total 4
-rw-r--r--    1 root     root            19 May  2 17:23 file_in_vdir
# podman exec foo cat /mydir/file_in_vdir
i am in the volume
# podman cp foo:/mydir/file_in_vdir file_from_foo
Error: error evaluating symlinks "": lstat /var/lib/containers/storage/overlay/e98c91535f29a51cf74d99f93ab1012486ffe792a035f0d8c273d6719d8a5f3f/merged/mydir/file_in_vdir: no such file or directory
```
podman @ pr #3041. Haven't actually tested master, will do so on request.

### PR DESCRIPTION
**Pull request by QiWang19**
Close #3059
enabls podman to copy files between the host machine and the volume related to a container.

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
This does not fully solve the problem as it was written. It works for named volumes only, and not directories bind-mounted in via `--volume` and `--mount type=bind`, and also not for tmpfs mounts (though I'm not sure if Docker can handle those either - needs checking)

**Comment by QiWang19** [comment]
hm, :eyes:   will check that

**Comment by QiWang19** [comment]
docker cp doesn't work for tmpfs.
I made changes to support named volumes, --mount volume, type=bind.

File: cmd/podman/cp.go [hunk 1]
```diff
@@ -350,3 +367,60 @@ func streamFileToStdout(srcPath string, srcfi os.FileInfo) error {
...
+
+func isBindMountDestName(path string, ctr *libpod.Container) (bool, specs.Mount) {
+	separator := string(os.PathSeparator)
+	if filepath.IsAbs(path) {
+		path = strings.TrimPrefix(path, string(os.PathSeparator))
+	}
+	if path == "" {
+		return false, specs.Mount{}
+	}
+	path = strings.Split(path, separator)[0]
```
Comment (mheon) [inline cmd/podman/cp.go]: Wait, how does this work? We split the original path on separators, then we compare it against the entire path of the volume (minus leading slash)? This doesn't seem like it makes sense.

Say I have two volumes, `/tmp/test/a` and `/tmp/test/b`, and I want to copy into `/tmp/test/b` - what's to prevent this from matching `/tmp/test/a` here?

File: cmd/podman/cp.go [hunk 2]
```diff
@@ -350,3 +367,60 @@ func streamFileToStdout(srcPath string, srcfi os.FileInfo) error {
...
+	for _, m := range ctr.Config().Spec.Mounts {
```
Comment (mheon) [inline cmd/podman/cp.go]: You also need to check if the mount is actually a bind mount

Comment (mheon) [reply cmd/podman/cp.go]: `m.Type == "bind"`

File: cmd/podman/cp.go (hunk 1 above)
Comment (QiWang19) [reply cmd/podman/cp.go]: also check the prefix? `if mDest == path && strings.HasPrefix(destpath, m.Destination)`
I'll also search the libraries.

File: cmd/podman/cp.go (hunk 2 above)
Comment (QiWang19) [reply cmd/podman/cp.go]: fixed

File: cmd/podman/cp.go (hunk 1 above)
Comment (QiWang19) [reply cmd/podman/cp.go]: @mheon, changed the path match logic `func matchVolumePath(path, target string) bool`, PTAL

File: cmd/podman/cp.go [hunk 3]
```diff
@@ -350,3 +367,71 @@ func streamFileToStdout(srcPath string, srcfi os.FileInfo) error {
...
+		}
+		mDest := strings.TrimPrefix(m.Destination, separator)
+		if matchVolumePath(path, mDest) {
+			return true, m
+		}
+	}
+	return false, specs.Mount{}
+}
+
+func matchVolumePath(path, target string) bool {
```
Comment (mheon) [inline cmd/podman/cp.go]: You probably want to do a path.Clean() on both paths first

Comment (QiWang19) [reply cmd/podman/cp.go]: fixed. PTAL @mheon

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM, would like to get a @mheon head nod.

**Comment by mheon** [comment]
Hold this until the CVE fix lands

**Comment by mheon** [comment]
I need to re-review once the CVE is fixed to make sure we don't regress

**Comment by mheon** [comment]
CVE fix is landed. Rebase and we can re-review

**Comment by QiWang19** [comment]
@mheon PTAL

**Comment by mheon** [comment]
@QiWang19 Mind rebasing to fix CI?

**Comment by rhatdan** [comment]
@mheon I think this is ready to go in?
